version: "3.6"
services:

 #сервис с фильмами
 films:
  #взять собранный образ
  image: vika-project
  #порты, порт докера - 3000, порт доступа -3666
  ports:
   - 3666:3000
  #если что-то вдруг пойдет не так)
  restart: always
